import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import SpaceBackground from "./components/SpaceBackground";
import { AppProvider, UserProvider } from "./UserContext"; // Import the AppProvider
import Header from "./components/Header";
import Footer from "./components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Name",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable}  antialiased bg-white text-black `}
      >
        {/* <video
          autoPlay
          loop
          muted
          playsInline
          className="fixed top-0 left-0 w-full h-full object-cover z-[-1]"
        >
          <source src="/bg1.mp4" type="video/mp4" />
          Your browser does not support the video tag.
        </video> */}
        <UserProvider>
          <Header />
          {/* <SpaceBackground/> */}
          <div className=" mt-24 min-h-[80vh]">
            {children}
          </div>
          {/* <Footer/> */}
        </UserProvider>
      </body>
    </html>
  );
}
